version: 1
jobs:      
  upload:
    steps:
      - npm install
      - npm run build
      - echo "Uploading File to stratus"
      - node scripts/upload-script.js
      
stages:
  - name: upload
    jobs:
      - upload

pipeline-when:
  equal:
    - << event.ref >>
    - refs/heads/release